Fixup actions for fork

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   #push:
   #  branches: [ "main" ]
-    
+
 env:
   UBUNTU_VERSION: 22.04
   BUILDX_NO_DEFAULT_ATTESTATIONS: 1
@@ -43,12 +43,6 @@ jobs:
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -91,7 +85,7 @@ jobs:
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
           tags: ${{ env.TAGS }}
-    
+
   nvidia-base:
     runs-on: ubuntu-latest
     strategy:
@@ -99,7 +93,6 @@ jobs:
       matrix:
         build:
           - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-base"}
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-cudnn8-devel"}
     steps:
       -
         name: Free Space
@@ -127,12 +120,6 @@ jobs:
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
       -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
         name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -143,7 +130,6 @@ jobs:
         name: Set tags
         run: |
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-          img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
           if [[ -z '${{ matrix.build.comfyui }}' ]]; then
               COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
           else
@@ -159,13 +145,8 @@ jobs:
                 # GHCR.io Tags
                 TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
                 # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-            fi
-            # Tag a devel build
-            if [[ ${{ matrix.build.cuda }} = *-devel ]]; then
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}-devel"
+                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -182,87 +163,85 @@ jobs:
           provenance: false
           tags: ${{ env.TAGS }}
 
-  amd-base:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.3.1", rocm: "6.0-runtime"}
-    steps:
-      -
-        name: Free Space
-        run: |
-          df -h
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf /usr/local/.ghcup
-          sudo rm -rf /usr/local/share/boost
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-          df -h
-      -
-        name: Env Setter
-        run: |
-          REPO=${GITHUB_REPOSITORY,,}
-          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
-          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
-        uses: actions/checkout@v3
-      -
-        name: Permissions fixes
-        run: |
-          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
-          chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
-        run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+  # amd-base:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build:
+  #         - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.3.1", rocm: "6.0-runtime"}
+  #   steps:
+  #     -
+  #       name: Free Space
+  #       run: |
+  #         df -h
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf /usr/local/.ghcup
+  #         sudo rm -rf /usr/local/share/boost
+  #         sudo rm -rf /usr/local/lib/android
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #         df -h
+  #     -
+  #       name: Env Setter
+  #       run: |
+  #         REPO=${GITHUB_REPOSITORY,,}
+  #         echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
+  #         echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
+  #     -
+  #       name: Checkout
+  #       uses: actions/checkout@v3
+  #     -
+  #       name: Permissions fixes
+  #       run: |
+  #         target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
+  #         chmod -R ug+rwX ${target}
+  #     -
+  #       name: Login to DockerHub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ vars.DOCKERHUB_USER }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     -
+  #       name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     -
+  #       name: Set tags
+  #       run: |
+  #           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+  #           if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+  #               COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+  #           else
+  #               COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+  #           fi
+  #           [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+  #           echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
+  #           base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                echo "Marking latest"
-                # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
-                # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
-            else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-            fi
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
-        uses: docker/build-push-action@v4
-        with:
-          context: build
-          build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
-            PYTHON_VERSION=${{ matrix.build.python }}
-            PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
-          push: true
-          provenance: false
-          tags: ${{ env.TAGS }}
+  #           if [[ ${{ matrix.build.latest }} == "true" ]]; then
+  #               echo "Marking latest"
+  #               # GHCR.io Tags
+  #               TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+  #               # Docker.io Tags
+  #           else
+  #               TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
+  #           fi
+  #           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+  #     -
+  #       name: Build and push
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: build
+  #         build-args: |
+  #           IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
+  #           PYTHON_VERSION=${{ matrix.build.python }}
+  #           PYTORCH_VERSION=${{ matrix.build.pytorch }}
+  #           COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
+  #         push: true
+  #         provenance: false
+  #         tags: ${{ env.TAGS }}
